- name: Configure arch machine
  hosts: localhost
  connection: local
  tasks:
    - name: pacman gotta go fast
      become: yes
      ini_file:
        path: /etc/pacman.conf
        section: options
        option: ParallelDownloads
        value: 10

    - name: run system update
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - system

    - name: install system packages
      become: yes
      pacman:
        name:
          - yay
          - zsh
          - neovim
          - tmux
          - fzf
          - base-devel
          - python
          - python2
          - ipython
          - go
          - docker
          - ansible
          - clang
          - cmake
          - rust
          - typescript
          - nodejs
          - npm
          - the_silver_searcher
          - helm
          - kubectl
          - abook
          - jupyter
          - neofetch
          - nload
          - xz
          - nmap
          - yarn
          - gdb
          - python-pytest
          - python-poetry
          - gopls
          - python-regex
          - jdk-openjdk
          - jdk11-openjdk
          - strace
          - flake8
          - rust-analyzer
          - python-isort
          - yapf
          - python-pynvim
          - deno
          - ansible-lint
          - smartmontools
          - lua
          - bind-tools

          # GUI related packages:
          - gdm
          - sway
          - waybar
          - gammastep
          - otf-font-awesome
          - alacritty
          - rofi
          - dmenu
          - code
          - grim
          - slurp
          - wl-clipboard
          - noto-fonts
          - noto-fonts-emoji
          - noto-fonts-cjk
          - noto-fonts-extra
          - ttf-liberation
          - ttf-droid
          - ttf-font-awesome
          - ttf-hack
          - torbrowser-launcher
          - pinta
          - telegram-desktop
          - capitaine-cursors

          # Printing and scanning
          # AUR package hpoj is also required
          - simple-scan
        state: present
      tags:
        - system

    - name: enable gdm
      become: yes
      systemd:
        name: gdm
        enabled: yes
      tags:
        - system

    - name: set default shell to zsh
      become: yes
      user:
        name: gorsil
        shell: /bin/zsh
      tags:
        - system
