- name: configure common stuff and dotfiles
  hosts: localhost
  connection: local
  tasks:
    - name: pacman gotta go fast
      become: yes
      ini_file:
        path: /etc/pacman.conf
        section: options
        option: ParallelDownloads
        value: 10

    - name: run system update
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - system

    - name: install system packages
      become: yes
      pacman:
        name:
          - yay
          - zsh
          - neovim
          - tmux
          - fzf
          - base-devel
          - python
          - python2
          - ipython
          - go
          - docker
          - ansible
          - clang
          - cmake
          - rust
          - typescript
          - nodejs
          - npm
          - the_silver_searcher
          - vim-jedi
          - python-jedi
          - helm
          - kubectl
          - w3m
          - lynx
          - links
          - elinks
          - abook
          - jupyter
          - neofetch
          - nload
          - xz
          - nmap
          - yarn
          - gdb
          - python-pytest
          - python-poetry
          - gopls
          - python-regex
          - jdk-openjdk
          - jdk11-openjdk
          - strace
          - flake8
          - rust-analyzer
          - python-isort
          - yapf
          - python-pynvim
          - deno
          - ansible-lint
          - smartmontools
          - lua

          # GUI related packages:
          - gdm
          - sway
          - waybar
          - gammastep
          - otf-font-awesome
          - alacritty
          - rofi
          - dmenu
          - code
          - grim
          - slurp
          - wl-clipboard
          - noto-fonts
          - noto-fonts-emoji
          - noto-fonts-cjk
          - noto-fonts-extra
          - ttf-liberation
          - ttf-droid
          - ttf-font-awesome
          - ttf-hack
          - torbrowser-launcher
          - pinta
          - telegram-desktop
          - capitaine-cursors
          - xdg-desktop-portal-wlr
        state: present
      tags:
        - system

    - name: install pip packages
      become: yes
      pip:
        name:
          - aiomoex
          - pandas
          - python-lsp-server[all]
          - gdown
      tags:
        - system

    - name: install npm packages
      become: yes
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - jsonlint
        - eslint
        - fixjson
      tags:
        - system


    - name: init git submodules
      shell: git submodule update --init --recursive
      tags:
        - dotfiles

    - name: create directories for configs
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      with_items:
        - ~/.config/alacritty
        - ~/.config/sway
        - ~/.config/nvim
        - ~/.icons/default
        - ~/notes
      tags:
        - dotfiles

    - name: emplace links to configs
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest}}"
        state: link
      with_items:
        - { src: "$PWD/vimrc", dest: "~/.config/nvim/init.vim" }

        - { src: "$PWD/pycodestyle", dest: "~/.config/pycodestyle" }
        - { src: "$PWD/waybar", dest: "~/.config/waybar" }
        - { src: "$PWD/alacritty.yml", dest: "~/.config/alacritty/alacritty.yml" }
        - { src: "$PWD/cursor.theme", dest: "~/.icons/default/index.theme" }

        - { src: "$PWD/zshrc", dest: "~/.zshrc" }
        - { src: "$PWD/oh-my-zsh", dest: "~/.oh-my-zsh" }
        - { src: "$PWD/zsh-syntax-highlighting", dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting" }
        - { src: "$PWD/zsh-autosuggestions", dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions" }
        - { src: "$PWD/zsh-256color", dest: "~/.oh-my-zsh/plugins/zsh-256color" }
        - { src: "$PWD/powerlevel10k", dest: "~/.oh-my-zsh/custom/themes/powerlevel10k" }
        - { src: "$PWD/p10k.zsh", dest: "~/.p10k.zsh" }
      tags:
        - dotfiles

    - name: create links to scripts, performed as root
      become: yes
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest}}"
        state: link
      with_items:
        - { src: "$PWD/scripts/usdrub.sh", dest: "/usr/local/bin/usdrub"}
      tags:
        - dotfiles

          # - name: "create dir for vim plug"
          #   file:
          #     path: /home/gorsil/.vim/autoload
          #     state: directory
          #   tags:
          #     - vim

          # - name: "download vim.plug"
          #   get_url:
          #     url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
          #     dest: /home/gorsil/.vim/autoload/plug.vim
          #   tags:
          #     - vim

          # - name: "install vim plugins, slow"
          #   shell: vim +PlugInstall +qa
          #   tags:
          #     - vim
