- name: Download, configure and link dotfiles
  hosts: localhost
  connection: local
  tasks:
    - name: init git submodules
      shell: git submodule update --init --recursive
      tags:
        - dotfiles

    - name: create directories for configs
      file:
        path: "{{ item }}"
        state: directory
        recurse: true
      with_items:
        - ~/.config/alacritty
        - ~/.config/sway
        - ~/.config/nvim
        - ~/.icons/default
        - ~/notes
      tags:
        - dotfiles

    - name: emplace links to configs
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest}}"
        state: link
      with_items:
        - {src: "$PWD/vimrc", dest: "~/.config/nvim/init.vim"}

        - {src: "$PWD/pycodestyle", dest: "~/.config/pycodestyle"}
        - {src: "$PWD/waybar", dest: "~/.config/waybar"}
        - {src: "$PWD/sway_config", dest: "~/.config/sway/config"}
        - {src: "$PWD/alacritty.yml", dest: "~/.config/alacritty/alacritty.yml"}
        - {src: "$PWD/cursor.theme", dest: "~/.icons/default/index.theme"}

        - {src: "$PWD/zshrc", dest: "~/.zshrc"}
        - {src: "$PWD/oh-my-zsh", dest: "~/.oh-my-zsh"}
        - {src: "$PWD/zsh-syntax-highlighting", dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"}
        - {src: "$PWD/zsh-autosuggestions", dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"}
        - {src: "$PWD/zsh-256color", dest: "~/.oh-my-zsh/plugins/zsh-256color"}
        - {src: "$PWD/powerlevel10k", dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"}
        - {src: "$PWD/p10k.zsh", dest: "~/.p10k.zsh"}
      tags:
        - dotfiles

    - name: create links to scripts, performed as root
      become: true
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - { src: "$PWD/scripts/usdrub.sh", dest: "/usr/local/bin/usdrub"}
      tags:
        - dotfiles
