- name: Configure system packages and services
  hosts: localhost
  connection: local
  tasks:
    - name: pacman gotta go fast
      become: yes
      ini_file:
        path: /etc/pacman.conf
        section: options
        option: ParallelDownloads
        value: 5
      tags:
        - system

    - name: run system update
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes
      tags:
        - system

    - name: install system packages
      become: yes
      pacman:
        name:
          # Python
          - python
          - python2
          - ipython
          - python-pytest
          - python-poetry
          - python-pip
          - python-pynvim
          - python-regex
          - python-isort
          - flake8
          - yapf

          # Dev
          - base-devel
          - clang
          - cmake
          - rust
          - typescript
          - go
          - nodejs
          - npm
          - nmap
          - yarn
          - gdb
          - gopls
          - jdk-openjdk
          - jdk11-openjdk
          - strace
          - deno
          - ansible-lint
          - yamllint
          - tree-sitter
          - rust-analyzer
          - lua
          - ruby-bundler
          - direnv
          - jupyter

          # Ops
          - docker
          - ansible
          - kubectl
          - helm
          - nload
          - vault

          # System
          - yay
          - zsh
          - neovim
          - tmux
          - fzf
          - the_silver_searcher
          - neofetch
          - xz
          - smartmontools
          - bind-tools
          - aws-cli

          # GUI related packages:
          - firefox
          - thunderbird

          - gdm
          - sway
          - waybar
          - gammastep
          - otf-font-awesome
          - alacritty
          - rofi
          - dmenu
          - code
          - grim
          - slurp
          - wl-clipboard
          - noto-fonts
          - noto-fonts-emoji
          - noto-fonts-cjk
          - noto-fonts-extra
          - ttf-liberation
          - ttf-droid
          - ttf-font-awesome
          - ttf-hack
          - torbrowser-launcher
          - pinta
          - telegram-desktop
          - capitaine-cursors
          - xdg-desktop-portal-wlr

          # Printing and scanning
          # AUR package hpoj is also required
          - simple-scan
        state: present
      tags:
        - system

    - name: enable gdm
      become: yes
      systemd:
        name: gdm
        enabled: yes
      tags:
        - system

    - name: set default shell to zsh
      become: yes
      user:
        name: gorsil
        shell: /bin/zsh
      tags:
        - system

    - name: install pip packages
      become: yes
      pip:
        name:
          - aiomoex
          - pandas
          - python-lsp-server[all]
          - gdown
      tags:
        - system

    - name: install npm packages
      become: yes
      npm:
        name: "{{ item }}"
        global: yes
      with_items:
        - jsonlint
        - eslint
        - fixjson
      tags:
        - system
